[package]
name = "wasi-rust-demo"
version = "0.1.0"
authors = ["Arnaud Tournier <ltearno@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
